messages:

  # 접두사
  prefix: "&8[&6캐시상점&8] &7"

  # 명령어 메세지
  command:

    # 콘솔에서 명령엇 사용 때
    console: "&c콘솔에서는 해당 명령어를 사용할 수 없습니다."

    # 명령어가 잘못 되었을 때
    wrong_command: "&c명령어가 잘못되었습니다."

    # 권한이 없을 때
    no_permission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

    # 해당 플레이어가 없을 때
    # {executor}    - 명령 실행자
    # {target}    - 타켓 플레이어
    no_player: "&c해당 플레이어({target})를 찾을 수 없습니다."

    # 캐시를 확인할 때
    check:

      # 자신의 캐시를 확인할 때
      # {player}    - 명령 실행자
      # {cash}      - 자신의 캐시
      self: "&a{player}님의 캐시는 &e{cash} &a입니다."

      # 다른 사람의 캐시를 확인할 때
      # {executor}  - 명령 실행자
      # {target}    - 타켓 플레이어
      # {cash}      - 타겟의 캐시
      other: "&a{target}님의 캐시는 &e{cash} &a입니다."

    # 캐시를 추가할 때
    # {executor}    - 명령 실행자
    # {target}      - 타켓 플레이어
    # {cash}        - 추가한 캐시
    add:
      # 명령 실행자에게 표시할 메세지
      executor: "&a{target}님에게 &e{cash} &a캐시를 추가하였습니다."

      # 타겟에게 표시할 메세지
      target: "&a{executor}님에 의해 &e{cash} &a캐시가 추가되었습니다."

    # 캐시를 제거할 때
    remove:

      # 성공했을 때
      # {executor}    - 명령 실행자
      # {target}      - 타켓 플레이어
      # {cash}        - 제거한 캐시
      success:
        # 명령 실행자에게 표시할 메세지
        executor: "&a{target}님의 &e{cash} &a캐시를 제거하였습니다."

        # 타겟에게 표시할 메세지
        target: "&a{executor}님에 의해 &e{cash} &a캐시가 제거되었습니다."

      # 잔액이 부족할 때
      # {executor}    - 명령 실행자
      # {target}      - 타켓 플레이어
      # {cash}        - 제거한 캐시
      # {balance}     - 타겟의 잔액
      no_balance: "&c{target}님의 잔액이 부족합니다. &e{cash} &c캐시를 제거하려 했으나 &e{balance} &c캐시밖에 없습니다."

    # 캐시를 설정할 때
    # {executor}    - 명령 실행자
    # {target}      - 타켓 플레이어
    # {cash}        - 설정한 캐시
    set:
      # 명령 실행자에게 표시할 메세지
      executor: "&a{target}님의 캐시를 &e{cash} &a로 설정하였습니다."

      # 타겟에게 표시할 메세지
      target: "&a당신의 캐시가 &e{cash} &a로 설정되었습니다."

    # 캐시를 초기화할 때
    # {executor}    - 명령 실행자
    # {target}      - 타켓 플레이어
    reset:
      # 명령 실행자에게 표시할 메세지
      executor: "&a{target}님의 캐시를 초기화하였습니다."

      # 타겟에게 표시할 메세지
      target: "&a당신의 캐시가 초기화되었습니다."

    # 도움말
    help:
      # /캐시 명령어
      cash:
        - "&a/캐시 [플레이어] &7- &f[플레이어] 또는 본인의 캐시를 확인합니다."
        - "&a/캐시 추가 <플레이어> <캐시> &7- &f플레이어의 캐시를 추가합니다."
        - "&a/캐시 제거 <플레이어> <캐시> &7- &f플레이어의 캐시를 제거합니다."
        - "&a/캐시 설정 <플레이어> <캐시> &7- &f플레이어의 캐시를 설정합니다."
        - "&a/캐시 초기화 <플레이어> &7- &f플레이어의 캐시를 초기화합니다."
        - "&a/캐시 도움말 &7- &f해당 도움말을 표시합니다."

      # /캐시상점 명령어
      cashshop:
        - "예정"

# 상품 로어
# {lore}      - 상품 기존 로어
# {buy}       - 구매 안내 로어
# {sell}      - 판매 안내 로어
lore:
  lore:
    - "{lore}"
    - ""
    - "&r&e&m===================="
    - ""
    - "{buy}"
    - "{sell}"
    - ""
    - "&6구매 &8》 &6좌클릭(1개) &6/ &6쉬프트 좌클릭(&764개)"
    - "&6판매 &8》 &6우클릭(1개) &6/ &6쉬프트 우클릭(&764개)"

  buy:
    can_buy: "&r&6구매 &8》 &7가격: &e{buy_price} &7캐시"
    cannot_buy: "&r&6구매 &8》 &c불가"

  sell:
    can_sell: "&r&6판매 &8》 &7가격: &e{sell_price} &7캐시"
    cannot_sell: "&r&6판매 &8》 &c불가"